version: "3.8"
services:
  bambusilver-storefront:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bambusilver-storefront
    ports:
      - "3020:80"
    networks:
      - bfs_default
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - bambusilver-proxy

  bambusilver-proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: bambusilver-proxy
    ports:
      - "3025:3025"
    networks:
      - bfs_default
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - proxy-data:/app/data

volumes:
  proxy-data:

networks:
  bfs_default:
    external: true
